security:
  queueItemAuthenticator:
    authenticators:
      - global:
          strategy: "systemAuthorizationStrategy"
jenkins:
  disableRememberMe: false
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  authorizationStrategy:
    projectMatrix:
      permissions:
      - "Agent/Build:anonymous"
      - "Job/Discover:anonymous"
      - "Overall/Administer:halkeye"
      - "Overall/Read:anonymous"
      - "Overall/Read:authenticated"
  securityRealm:
    ldap:
      configurations:
        - server: openldap.openldap.svc.cluster.local
          rootDN: "ou=users,dc=gavinmogan,dc=com"
          managerDN: "cn=admin,dc=gavinmogan,dc=com"
          managerPasswordSecret: 'V4Lhx3CCGGhCjyHlSuJ'
          #userSearch: "cn="
          #userSearchBase: "ou=users,dc=gavinmogan,dc=com"
      cache:
        size: 100
        ttl: 10
      userIdStrategy: CaseInsensitive
      groupIdStrategy: CaseSensitive

  numExecutors: 0
  clouds:
    - kubernetes:
        containerCapStr: "10"
        jenkinsTunnel: "jenkins-agent:50000"
        jenkinsUrl: "http://jenkins:8080"
        maxRequestsPerHostStr: "32"
        name: "kubernetes"
        namespace: "jenkins"
        podLabels:
        - key: "jenkins/jenkins-jenkins-slave"
          value: "true"
        serverUrl: "https://kubernetes.default"
        templates:
        - containers:
          - alwaysPullImage: true
            args: "^${computer.jnlpmac} ^${computer.name}"
            envVars:
            - envVar:
                key: "JENKINS_URL"
                value: "http://jenkins.jenkins.svc.cluster.local:8080"
            image: "halkeye/dind-jenkins-slave:3.40-1-dind-1"
            livenessProbe:
              failureThreshold: 0
              initialDelaySeconds: 0
              periodSeconds: 0
              successThreshold: 0
              timeoutSeconds: 0
            name: "jnlp"
            privileged: true
            resourceLimitCpu: "1.0"
            resourceLimitMemory: "2048Mi"
            resourceRequestCpu: "1.0"
            resourceRequestMemory: "2048Mi"
            # resourceLimitCpu: "1024m"
            # resourceLimitMemory: "1024Mi"
            # resourceRequestCpu: "1024m"
            # resourceRequestMemory: "1024Mi"
            ttyEnabled: true
            workingDir: "/home/jenkins/agent"
          hostNetwork: false
          label: "jenkins-agent"
          name: "default"
          namespace: "jenkins"
          nodeUsageMode: "NORMAL"
          serviceAccount: "default"
          # volumes:
          # - hostPathVolume:
          #     hostPath: "/var/run/docker.sock"
          #     mountPath: "/var/run/docker.sock"
          yamlMergeStrategy: "override"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
unclassified:
  bitbucketEndpointConfiguration:
    endpoints:
    - bitbucketCloudEndpoint:
        credentialsId: "bitbucket-halkeye"
        enableCache: false
        manageHooks: true
        repositoriesCacheDuration: 0
        teamCacheDuration: 0
  location:
    adminAddress: "jenkins@g4v.dev"
    url: "https://ci.g4v.dev/"
  extendedEmailPublisher:
    defaultReplyTo: "jenkins@g4v.dev"
    smtpPort: "25"
    smtpServer: "odin.kodekoan.com"
  gitHubPluginConfig:
    configs:
      - credentialsId: "github-admin-halkeye"
    hookUrl: "https://ci.g4v.dev/github-webhook/"
  githubPullRequests:
    publishedURL: "https://ci.g4v.dev"
  mailer:
    replyToAddress: "jenkins@gavinmogan.com"
    smtpHost: "odin.kodekoan.com"
    smtpPort: "25"
  globalLibraries:
    libraries:
      - name: "github.com/halkeye/jenkins-shared-library"
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/halkeye/jenkins-shared-library"
jobs:
  - url: https://raw.githubusercontent.com/halkeye/jenkins-jobs/master/jobs.groovy
