security:
  queueItemAuthenticator:
    authenticators:
      - global:
          strategy: "triggeringUsersAuthorizationStrategy"
jenkins:
  remotingSecurity:
    enabled: true
  disableRememberMe: false
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  authorizationStrategy:
    projectMatrix:
      permissions:
      - "Agent/Build:anonymous"
      - "Job/Discover:anonymous"
      - "Overall/Administer:halkeye"
      - "Overall/Read:anonymous"
      - "Overall/Read:authenticated"
  securityRealm:
    oic:
      authorizationServerUrl: "https://keycloak.g4v.dev/auth/realms/${OIC_AUTH_REALM}/protocol/openid-connect/auth"
      clientId: "${OIC_AUTH_CLIENT_ID}"
      clientSecret: "${OIC_AUTH_CLIENT_SECRET}"
      disableSslVerification: false
      endSessionEndpoint: "https://keycloak.g4v.dev/auth/realms/${OIC_AUTH_REALM}/protocol/openid-connect/logout"
      escapeHatchEnabled: false
      logoutFromOpenidProvider: true
      scopes: "web-origins address phone openid roles profile offline_access microprofile-jwt email"
      tokenServerUrl: "https://keycloak.g4v.dev/auth/realms/${OIC_AUTH_REALM}/protocol/openid-connect/token"
      userInfoServerUrl: "https://keycloak.g4v.dev/auth/realms/${OIC_AUTH_REALM}/protocol/openid-connect/userinfo"
      # wellKnownOpenIDConfigurationUrl: "https://keycloak.g4v.dev/auth/realms/${OIC_AUTH_REALM}/.well-known/openid-configuration"
      userNameField: "preferred_username"
      emailFieldName: "email"
      fullNameFieldName: "name"
      groupsFieldName: "group-membership"
  numExecutors: 0
  clouds:
    - kubernetes:
        containerCapStr: "3"
        jenkinsTunnel: "jenkins-agent:50000"
        jenkinsUrl: "http://jenkins:8080"
        maxRequestsPerHostStr: "32"
        name: "kubernetes"
        namespace: "jenkins"
        podLabels:
        - key: "jenkins/jenkins-jenkins-slave"
          value: "true"
        serverUrl: "https://kubernetes.default"
        templates:
        - containers:
          - alwaysPullImage: true
            args: "^${computer.jnlpmac} ^${computer.name}"
            command: "/usr/local/bin/wrapdocker"
            envVars:
            - envVar:
                key: "JENKINS_URL"
                value: "http://jenkins.jenkins.svc.cluster.local:8080"
            image: "halkeye/dind-jenkins-slave:3.40-1-dind-1"
            livenessProbe:
              failureThreshold: 0
              initialDelaySeconds: 0
              periodSeconds: 0
              successThreshold: 0
              timeoutSeconds: 0
            name: "jnlp"
            privileged: true
            resourceLimitCpu: "2.0"
            resourceLimitMemory: "2048Mi"
            resourceRequestCpu: "2.0"
            resourceRequestMemory: "1024Mi"
            ttyEnabled: false
            workingDir: "/home/jenkins/agent"
          hostNetwork: false
          idleMinutes: 30
          idleMinutesStr: "30"
          label: "jenkins-agent"
          name: "default"
          namespace: "jenkins"
          nodeUsageMode: "NORMAL"
          podRetention: "onFailure"
          serviceAccount: "default"
          workspaceVolume:
            emptyDirWorkspaceVolume:
              memory: true
          volumes:
           - hostPathVolume:
               hostPath: "/var/run/docker.sock"
               mountPath: "/var/run/docker.sock"
          yaml: |
            spec:
              dnsConfig:
                options:
                  - name: ndots
                    value: "1"
          yamlMergeStrategy: "override"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
unclassified:
  bitbucketEndpointConfiguration:
    endpoints:
    - bitbucketCloudEndpoint:
        credentialsId: "bitbucket-halkeye"
        enableCache: false
        manageHooks: true
        repositoriesCacheDuration: 0
        teamCacheDuration: 0
  location:
    adminAddress: "jenkins@g4v.dev"
    url: "https://ci.g4v.dev/"
  email-ext:
    defaultReplyTo: "jenkins@g4v.dev"
    mailAccount:
      smtpPort: "25"
      smtpHost: "${SMTP_SERVER}"
  gitHubPluginConfig:
    configs:
      - credentialsId: "github-admin-halkeye"
    hookUrl: "https://ci.g4v.dev/github-webhook/"
  githubPullRequests:
    publishedURL: "https://ci.g4v.dev"
  mailer:
    replyToAddress: "jenkins@g4v.dev"
    smtpHost: "${SMTP_SERVER}"
    smtpPort: "25"
  globalLibraries:
    libraries:
      - name: "github.com/halkeye/jenkins-shared-library"
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/halkeye/jenkins-shared-library"
jobs:
  - url: https://raw.githubusercontent.com/halkeye/jenkins-jobs/master/jobs.groovy
