name: Build Docker image

on:
  pull_request:
    branches: [master, main]

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@0f8c876bafbf5dbce05c36682ec68e9a0274a48a
        with:
          images: halkeye/jenkins

      - name: Build Docker image
        uses: docker/build-push-action@9311bf5263ae5b36f3ec67aff768790c6e2344ad
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
