name: Build Docker image

on:
  pull_request:
    branches: [master, main]

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@79f06a31c0239ef7cd295f017ff96abdf7bbe84d
        with:
          images: halkeye/jenkins

      - name: Build Docker image
        uses: docker/build-push-action@4e4ee680f69700760d5620a94c020aef883043aa
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
